name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Workflow akan dijalankan saat ada push ke branch main
  pull_request:
    branches:
      - main  # Workflow juga akan dijalankan saat ada pull request ke branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan workflow di mesin Ubuntu terbaru

    steps:
      # Step 1: Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js (atau sesuai dengan stack yang Anda gunakan)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Sesuaikan dengan versi Node.js yang Anda gunakan

      # Step 3: Install dependencies (jika menggunakan Node.js)
      - name: Install dependencies
        run: npm install

      # Step 4: Jalankan build atau test (misalnya untuk Node.js)
      - name: Run build or test
        run: npm run build  # Jika Anda memiliki script build di package.json

      # Step 5: Dockerize (contoh untuk Node.js)
      - name: Build Docker image
        run: |
          docker build -t my-app .
          docker tag my-app:latest yourdockerhubusername/my-app:latest
      
      # Step 6: Push Docker image ke Docker Hub (jika diperlukan)
      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yourdockerhubusername/my-app:latest
